####################################
#
# Плагин создан для FraqMine
# Использование на своем сервере разрешено.
# Использование в коммерческих целях запрещено!
#
# Создатель - ReoGenT (https://vk.com/dzekmant)
#
# mc.fraqmine.ru
####################################

enable_hammer: true
players: